export enum RoutesEnum {
  StartPage = '/',
  UserLogin = '/login',
  RegisterCooperation = '/register-cooperation',
  RegisterUser = '/register-user',
  ManageUser = '/main/manage-user',
  MainPage = '/main',
  Cooperation = '/main/cooperation',
  ManageApartments = '/main/cooperation/:id',
  ApartmentInfo = '/main/cooperation/:id/:apartment',
  Polls = '/main/polls',
  InvitationSection = '/main/invitations',
  PageErrorInvintation = '/broken-link',
  PollInfo = '/main/polls/:id',
  FinanceSection = '/main/finance',
  TarrifsCalculation = '/main/finance/tarrifs-calculation',
  TariffsManagement = '/main/finance/tariffs-management',

  NotFound = '/:catchAll(.*)',
}
